/*
Copyright (c) 1995-2008 held by the author(s).  All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
    * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (http://www.nps.edu and http://www.movesinstitute.org)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/
package viskit;

import java.awt.Dialog;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.WindowConstants;

/**
 * ViskitProjectGenerationDialog2.java
 * 
 * Edit this GUI with Netbeans Matisse
 * 
 * @author Mike Bailey
 * @since Aug 2008
 * @version $Id: $
 */
public class ViskitProjectGenerationDialog2 extends javax.swing.JPanel
{
  private File created;
  private static JDialog dialog;
  public static void showDialog()
  {
    ViskitProjectGenerationDialog2 panel = new ViskitProjectGenerationDialog2();
    dialog = new JDialog((Dialog)null,true);  // modal
    dialog.setContentPane(panel);
    dialog.pack();
    dialog.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
    // Dialog will appear in center screen
    dialog.setLocationRelativeTo(null);
    dialog.setVisible(true);
  }
  
    private ViskitProjectGenerationDialog2() {
        initComponents();
        setDefaults();
    }
    
    private void setDefaults()
    {
        String defaultProjectDir = ViskitProject.DEFAULT_VISKIT_PROJECTS_DIR;
        File f = new File(defaultProjectDir);
        if(!f.exists()) {
          f.mkdirs();
          created = f;
        }
        chooser.setCurrentDirectory(f);
        File projDirFile = findFreeFileName(f,ViskitProject.DEFAULT_PROJECT);
        chooser.setSelectedFile(projDirFile);
    }

    File findFreeFileName(File parent, String s)
    {
      File f;
      String idxStr = "";
      int idx = 0;
      do {
        f = new File(parent,s+idxStr);
        idxStr = "_"+idx++;
      } while (f.exists());
      return f;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    chooser = new javax.swing.JFileChooser();
    createButt = new javax.swing.JButton();
    resetButt = new javax.swing.JButton();
    quitButt = new javax.swing.JButton();

    chooser.setControlButtonsAreShown(false);
    chooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

    createButt.setText("Create");
    createButt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        createButtActionPerformed(evt);
      }
    });

    resetButt.setText("Reset to default location");
    resetButt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        resetButtActionPerformed(evt);
      }
    });

    quitButt.setText("Quit Viskit");
    quitButt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        quitButtActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(210, Short.MAX_VALUE)
        .addComponent(quitButt)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(resetButt)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(createButt)
        .addContainerGap())
      .addComponent(chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(createButt)
          .addComponent(resetButt)
          .addComponent(quitButt))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

private void quitButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtActionPerformed
  if(created != null) {
    created.delete();
  }
  System.exit(0);
}//GEN-LAST:event_quitButtActionPerformed

private void resetButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtActionPerformed
  setDefaults();
}//GEN-LAST:event_resetButtActionPerformed

private void createButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtActionPerformed
  File selF = chooser.getSelectedFile();
  File parent = chooser.getCurrentDirectory();
  //String fn = chooser.getn
  ViskitConfig.instance().setVal(ViskitConfig.PROJECT_HOME_KEY, selF.getParent());
  ViskitProject.MY_VISKIT_PROJECTS_DIR = selF.getParent();
  ViskitProject.DEFAULT_PROJECT = selF.getName();
  dialog.setVisible(false);
}//GEN-LAST:event_createButtActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JFileChooser chooser;
  private javax.swing.JButton createButt;
  private javax.swing.JButton quitButt;
  private javax.swing.JButton resetButt;
  // End of variables declaration//GEN-END:variables

}
